### ISSUE TITLE
Zombie always calling the example command even after removal from config.yml

### ISSUE THREAD

**Issue by ghost** [jaqobb-mineground/rewardable-activities#9]
This is a weird one. I have a config.yml set up to reward entity kills, and only entity kills; the entire file is pasted below. There are no commands in the file, yet when I defeat a zombie, rewardable-activities **still** executes the example "Player has defeated a zombie! (default)" command, which is nowhere in my config file. The only way to make that command go away is to define some **other** command when killing a zombie, which then is executed instead of the default "say". My guess is that it's somehow reading the built-in config.yml and retaining some of it before reading the one in the server.

```
entity:
  ownership-check:
    breed: true
    spawner: true
  kill:
    zombie:
      default:
        chance: 100.0
        minimum-economy: 1.0
        maximum-economy: 5.0
    husk:
      default:
        chance: 100.0
        minimum-economy: 1.0
        maximum-economy: 5.0
    drowned:
      default:
        chance: 100.0
        minimum-economy: 1.0
        maximum-economy: 5.0
    zombie_villager:
      default:
        chance: 100.0
        minimum-economy: 1.0
        maximum-economy: 5.0

    spider:
      default:
        chance: 100.0
        minimum-economy: 1.0
        maximum-economy: 5.0
    cave_spider:
      default:
        chance: 100.0
        minimum-economy: 1.0
        maximum-economy: 5.0

    skeleton:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    stray:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    wither_skeleton:
      default:
        chance: 100.0
        minimum-economy: 10.0
        maximum-economy: 20.0

    silverfish:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    guardian:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0

    blaze:
      default:
        chance: 100.0
        minimum-economy: 10.0
        maximum-economy: 20.0
    shulker:
      default:
        chance: 100.0
        minimum-economy: 10.0
        maximum-economy: 20.0

    creeper:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    ghast:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    phantom:
      default:
        chance: 100.0
        minimum-economy: 25.0
        maximum-economy: 50.0

    # Mobs with no rewards due to mass spawning mechanics.
    enderman:
      default:
        chance: 100.0
        minimum-economy: 0.0
        maximum-economy: 0.0
    zombified_piglin:
      default:
        chance: 100.0
        minimum-economy: 0.0
        maximum-economy: 0.0

    # Mobs with small rewards due to splitting.
    slime:
      default:
        chance: 100.0
        minimum-economy: 0.0
        maximum-economy: 1.0
    magma_cube:
      default:
        chance: 100.0
        minimum-economy: 0.0
        maximum-economy: 1.0

    piglin:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    hoglin:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0
    zoglin:
      default:
        chance: 100.0
        minimum-economy: 5.0
        maximum-economy: 10.0

    witch:
      default:
        chance: 100.0
        minimum-economy: 10.0
        maximum-economy: 20.0
    pillager:
      default:
        chance: 100.0
        minimum-economy: 10.0
        maximum-economy: 20.0
    vindicator:
      default:
        chance: 100.0
        minimum-economy: 10.0
        maximum-economy: 20.0

    # Raid mobs
    piglin_brute:
      default:
        chance: 100.0
        minimum-economy: 50.0
        maximum-economy: 100.0
    ravager:
      default:
        chance: 100.0
        minimum-economy: 50.0
        maximum-economy: 100.0
    evoker:
      default:
        chance: 100.0
        minimum-economy: 50.0
        maximum-economy: 100.0
    elder_guardian:
      default:
        chance: 100.0
        minimum-economy: 100.0
        maximum-economy: 250.0
    wither:
      default:
        chance: 100.0
        minimum-economy: 250.0
        maximum-economy: 500.0
    ender_dragon:
      default:
        chance: 100.0
        minimum-economy: 500.0
        maximum-economy: 1000.0
```
